name: Test Formalities

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Test Formalities
    uses: openwrt/actions-shared-workflows/.github/workflows/formal.yml@main
    
    with:
      config-path: .config
