name: Test Formalities

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Test Formalities
    uses: openwrt/actions-shared-workflows/.github/workflows/formal.yml@main
    
  post-build:
    runs-on: ubuntu-latest
    needs: build  # 确保 build 任务完成后才执行
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Ensure `.config` is correctly placed
      #  run: |
      #    cp .config .config

      - name: Upload OpenWrt firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt-Firmware
          path: bin/targets/
