name: Build & Release OpenWRT Firmware

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc wget unzip python3

      - name: Build OpenWRT firmware
        run: |
          # 这里替换为你自己的 OpenWRT 编译命令
          - name: "多线程编译"
            cd $GITHUB_WORKSPACE/openwrt
            echo -e "$(nproc) threads for compilation..."
            make -j$(nproc)
          - name: "失败时使用单线程编译"
            if: failure()
            run: |
            cd $GITHUB_WORKSPACE/openwrt
            make -j1 V=s
        
          #make defconfig
          #make -j$(nproc)

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: bin/targets/**/*.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: bin/targets/**/*.bin

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
